version: '3'

services:
  php:
    image: fsilva/php:8.0-cli
    volumes:
     - ./:/usr/src/app
    working_dir: /usr/src/app
  docs:
    image: nginx
    ports:
      - 80
    volumes:
      - ./docs/build:/usr/share/nginx/html
